name: Website Monitor

on:
  schedule:
    - cron: '*/15 * * * *'   # alle 15 Minuten
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      # Repo auschecken
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Website prüfen und HTML-Datei erstellen
      - name: Prüfe Website und erstelle HTML
        id: ping
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://mattisweb.de)
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          if [ "$STATUS" -eq 200 ]; then
            MESSAGE="Website ist OK ✅"
            COLOR="green"
          else
            MESSAGE="Website ist DOWN ❌"
            COLOR="red"
          fi

          cat <<EOF > status.html
          <!DOCTYPE html>
          <html lang="de">
          <head>
            <meta charset="UTF-8">
            <title>Website Status</title>
          </head>
          <body>
            <h1 style="color:$COLOR;">$MESSAGE</h1>
            <p>Letzter Check: $TIMESTAMP</p>
          </body>
          </html>
          EOF

      # HTML-Datei committen und pushen
      - name: Commit & Push HTML-Datei
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add status.html
          git commit -m "Update Website Status" || echo "Keine Änderungen zum committen"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/INEVERSTOPMEWING/status.git HEAD:main

